- name: Create confd directories
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - /etc/confd/conf.d
    - /etc/confd/templates

- name: Install confd
  get_url:
    url: https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64
    dest: /usr/local/bin/confd
    mode: 0700
